version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanderlust-app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
